name: githubsearch
description: "GitHub Search Application project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  http: ^1.4.0

  go_router: ^15.2.4

  flutter_riverpod: ^2.6.1

  json_annotation: ^4.9.0

  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.5.4

  freezed: ^3.0.6

  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
